services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=smdn-my-waifu'
      - 'POSTGRES_PASSWORD=supersecretpassword'
      - 'POSTGRES_USER=silvermaiden'
    ports:
      - '5432:5432'
  rabbitmq:
    image: 'rabbitmq:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=uknowmesowell'
      - 'RABBITMQ_DEFAULT_USER=silvermaiden'
    ports:
      - '5672'
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
